### ISSUE TITLE
MOLPay swift Example/MOLPayExample/BridgingObjC.h:12:9: 'MOLPayLibrary/MOLPayLib.h' file not found

### ISSUE THREAD

**Issue by zulfajuniadi** [MOLPay/Mobile_SDK-iOS#11]
Version: 4.0.6.1

I just downloaded then click ran, the following error is shown:

`MOLPay swift Example/MOLPayExample/BridgingObjC.h:12:9: 'MOLPayLibrary/MOLPayLib.h' file not found`

![header file not found](http://i.imgur.com/gfaWA2Z.png)

Same for both swift and objective c

**Comment by arifjusohMOLPay** [comment]
Hey there, please try re-download again, I made some changes that should fix this issue.. :smile:
