### ISSUE TITLE
Payment options over HTTPS to support ios9 App Transport Security

### ISSUE THREAD

**Issue by baraabourghli** [MOLPay/Mobile_SDK-iOS#12]
Can you please help to fix this!?

**Comment by tekjau** [comment]
Our developer will evaluate on this

**Comment by arifjusohMOLPay** [comment]
Hi @baraabourghli,

You may add the following inside your Info.plist

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>abmb.com.my</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>molpay.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by baraabourghli** [comment]
Hi @arifjusohMOLPay , we already have added exceptions thanks, but is it possible to update the pod in the future?

**Comment by arifjusohMOLPay** [comment]
Hi @baraabourghli, we do have plan to update pod but currently we're on a tight schedule in improving the backend. We'll update a.s.a.p when its ready.

**Comment by arifjusohMOLPay** [comment]
Hi @baraabourghli,
You may remove the following key inside your project Info.plist and let met know if there's any issue. I've tested so far wont face issue for that domain since its already upgraded the protocol.

```
            <key>abmb.com.my</key>
            <dict>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
```
