### ISSUE TITLE
Crash when search bank country.

### ISSUE THREAD

**Issue by tranngoclinh88** [MOLPay/Mobile_SDK-iOS#13]
Here is the issue detail.

![screen shot 2015-11-03 at 11 43 46 am](https://cloud.githubusercontent.com/assets/1511264/10901413/647048ea-8220-11e5-9cb4-66c9b359f28d.png)

**Comment by arifjusohMOLPay** [comment]
Latest version release (4.0.6.3) should be able to fixed this.

Let me know if this issue still happen
