### ISSUE TITLE
Crash when select Credit Card.

### ISSUE THREAD

**Issue by tranngoclinh88** [MOLPay/Mobile_SDK-iOS#14]
Here is the issue detail.

![screen shot 2015-11-03 at 11 50 11 am](https://cloud.githubusercontent.com/assets/1511264/10901444/1371a910-8221-11e5-9716-9fc00dec1043.png)

**Comment by arifjusohMOLPay** [comment]
Latest version release (4.0.6.3) should be able to fixed this.

Let me know if this issue still happen
