### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by tranngoclinh88** [MOLPay/Mobile_SDK-iOS#16]
I updated to the newest SDK 4.0.6.3 and can not build project.
Here is the error.

duplicate symbol _OBJC_CLASS_$_CreditCardNoTokenViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_CreditCardTokenViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_Luhn in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_MOLPayLib in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_PaymentChannelViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_PaymentInfoViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKAPIHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKAmountCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKBTNCountryCodeCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKBTNCreditCardTokenCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKBankLogoCardType in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKBankNameCountryCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKBasedHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKCCViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKCVVDateCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKCacheHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKChannelHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKCreditCardCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKDefaultTableViewCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKDeviceInformation in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKImageCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKImageHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKJSHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKKeyboardHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKKeyboardToolbar in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKLoadingCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKLoadingView in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKLog in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKOptionCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKParameterHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKPaymentDetail in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKReceiptViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKResultHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKRowObject in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKSectionObject in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKTextFieldCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKTextViewCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKUIMethods in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKUpdateHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SDKValidation in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_SearchBankCountryTableViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_CLASS_$_WebViewViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_CreditCardNoTokenViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_CreditCardTokenViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_Luhn in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_MOLPayLib in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_PaymentChannelViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_PaymentInfoViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKAPIHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKAmountCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKBTNCountryCodeCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKBTNCreditCardTokenCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKBankLogoCardType in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKBankNameCountryCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKBasedHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKCCViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKCVVDateCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKCacheHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKChannelHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKCreditCardCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKDefaultTableViewCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKDeviceInformation in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKImageCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKImageHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKJSHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKKeyboardHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKKeyboardToolbar in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKLoadingCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKLoadingView in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKLog in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKOptionCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKParameterHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKPaymentDetail in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKReceiptViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKResultHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKRowObject in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKSectionObject in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKTextFieldCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKTextViewCell in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKUIMethods in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKUpdateHandler in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SDKValidation in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_SearchBankCountryTableViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
duplicate symbol _OBJC_METACLASS_$_WebViewViewController in:
    /Users/TranNgocLinh88/Documents/Projects/Company projects/VUS/ChatApp/iOS_trunk/uChat/Vendor/MOLPaySDK/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)
ld: 84 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by arifjusohMOLPay** [comment]
Hi @tranngoclinh88 , 
May I know how you update the SDK? 
Im unable to replicate this.

**Comment by tranngoclinh88** [comment]
I just update the newest version and it runs. Thanks.

**Comment by arifjusohMOLPay** [comment]
Hi @tranngoclinh88,
Good to know that you're able to run it.

Closing this issue.
