### ISSUE TITLE
bitcode

### ISSUE THREAD

**Issue by fahrulazmi** [MOLPay/Mobile_SDK-iOS#17]
Encountered issue when archived with bitcode.
```ld: bitcode bundle could not be generated because '/xxx/MOLPayLibrary.embeddedframework/MOLPayLibrary.framework/MOLPayLibrary(MOLPayLibrary)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64```

**Comment by arifjusohMOLPay** [comment]
Hi @fahrulazmi , 
I've update the sdk with bitcode build. 

Let me know if you face any error. 

Thanks and regards :smile:
