### ISSUE TITLE
URL Scheme issue

### ISSUE THREAD

**Issue by iosSlacker** [MOLPay/Mobile_SDK-iOS#18]
What is the url scheme that required by the payment request? Is it obtainable through merchant account or what? Thanks

**Comment by arifjusohMOLPay** [comment]
Hi @iosSlacker, 
>What is the url scheme that required by the payment request? Is it obtainable through merchant account or what? 

For your information:
**URL Sheme** is an Inter-App Communication. Kindly refer [here] (https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html) for details from Apple.

For the usage in MOLPay SDK, you may refer **Chapter 4. MOLWallet Integration**. 

> Merchant apps need to specify their own URL scheme and pass it in the paymentRequestDict (Please refer to chapter 3.3.1). URL Scheme will be use to handle callbacks in MOLWallet channel.

**Comment by iosSlacker** [comment]
Is it necessary if the apps not using MOLWallet? Currently the objective C example project unable to run even with the merchant information setup

**Comment by arifjusohMOLPay** [comment]
Hi again @iosSlacker,
Its not compulsory to use MOLWallet.
 
Could you share me the error in new issue?

**Comment by iosSlacker** [comment]
Hi @arifjusohMOLPay ,
This is the error when I use the "multi" channel and click on the "Payment Options".
![simulator screen shot dec 9 2015 12 18 23 pm](https://cloud.githubusercontent.com/assets/16206288/11676660/8e96aad6-9e6f-11e5-8ffc-d7a3448496bc.png)

If I change the channel to "maybank2u" or "hlb", the payment screen just loading forever
