### ISSUE TITLE
no back button (v4.0.6.5)

### ISSUE THREAD

**Issue by pankkor** [MOLPay/Mobile_SDK-iOS#20]
There back button is not visible
![no-back-button](https://cloud.githubusercontent.com/assets/3875331/12037710/7dfead7e-ae49-11e5-9025-3c3d4ffaf32d.png)
But if you press on the left corner of navigation bar you still get a quit alert
![quit-alert](https://cloud.githubusercontent.com/assets/3875331/12037743/d2d367a4-ae49-11e5-9404-397efc490f62.png)
Maybe back button should be visible?

**Comment by arifjusohMOLPay** [comment]
Hi @pankkor ,

Which file did you drag/import into your project?
*MOLPayLibrary.embeddedframework* **or** *MOLPayLibrary.framework* 

if the later, 
i advised you to drag/import **MOLPayLibrary.embeddedframework** into your project.

**Comment by pankkor** [comment]
@arifjusoh Yes, I imported MOLPayLibrary.embeddedframework. I've tried to checkout the repo again and repeat the same steps I did last time and I can see a back button now. I have no clue what I did wrong last time.
It can be a big improvement to add podspec to eliminate error connected to manual importing framework to a project.
Anyway, thank you for you help.
