### ISSUE TITLE
Choose CIMB Click and get CFNetwork SSLHandshake failed Error

### ISSUE THREAD

**Issue by engboon** [MOLPay/Mobile_SDK-iOS#21]
here is more details
2016-01-14 01:04:32.259 MyApp[4566:1863678] CFNetwork SSLHandshake failed (-9824)
2016-01-14 01:04:32.261 MyApp[4566:1863855] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

And the page will keep loading.

![capture](https://cloud.githubusercontent.com/assets/2778752/12301634/03727904-ba5c-11e5-97bf-f99fd441a916.PNG)
Added molpay.com as the exception domain.

**Comment by clewlb** [comment]
@engboon 
Due to CIMB Bank still uses old certs, you may use workaround below,

<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>www.cimbclicks.com.my</key>
            <dict>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>

**Comment by engboon** [comment]
Hi @clewlb , can please help to check other banks as well?

**Comment by clewlb** [comment]
@engboon So far we have not received any complaints for other banks. You are good with only CIMB bank workaround for now. Should you discover something new, please let us know. Thank you.

**Comment by engboon** [comment]
@clewlb Just tested public bank under FPX also the same
