### ISSUE TITLE
podspec please...

### ISSUE THREAD

**Issue by fahrulazmi** [MOLPay/Mobile_SDK-iOS#7]

**Comment by clewlb** [comment]
@fahrulazmi ,
We are planning to roll out our iOS SDK on cocoapods soon, stay tune with us, and thank you for your valuable feedback. - MOLPay Tech Team

**Comment by pankkor** [comment]
@clewlb when can we expect a podspec?

**Comment by clewlb** [comment]
@pankkor @fahrulazmi,
We have rolled out our cocoapods sdk at https://github.com/MOLPay/Mobile_SDK-iOS_Cocoapods, you may install it with pod "MOLPaySDK". Thanks for your support. - MOLPay Tech Team

**Comment by pankkor** [comment]
@clewlb thanks for you response. Does it mean that https://github.com/MOLPay/Mobile_SDK-iOS and  https://github.com/MOLPay/Mobile_SDK-iOS_Cocoapods will continue to live in parallel?

**Comment by clewlb** [comment]
Yes they will.
